"""Headless Python API for Unified3D operations and runtime clients."""

from .analysis import (
    ANALYSIS_SCHEMA,
    AnalysisComparisonResult,
    AnalysisRecord,
    AnalysisRecordDict,
    AnalysisValidationResult,
    ContractIssue,
    canonicalize_analysis,
    compare_analyses,
    compare_analyses_oracle,
    normalize_analysis,
    validate_analysis,
)
from .runtime import (
    AssetHandle,
    CanonicalGeometryFingerprint,
    ConvertGlbToFbxResult,
    GlbToFbxConversionReport,
    LoadAssetResult,
    NormalizeSpatialResult,
    Provenance,
    ReleaseAssetResult,
    RuntimeComparisonResult,
    RuntimeRPCError,
    SpatialNormalizationReport,
    SpatialMappingSample,
    SkinTransferReport,
    SkinTransferResult,
    Unified3DClient,
)

__all__ = [
    "ANALYSIS_SCHEMA",
    "AnalysisComparisonResult",
    "AnalysisRecord",
    "AnalysisRecordDict",
    "AnalysisValidationResult",
    "AssetHandle",
    "CanonicalGeometryFingerprint",
    "ConvertGlbToFbxResult",
    "ContractIssue",
    "GlbToFbxConversionReport",
    "LoadAssetResult",
    "NormalizeSpatialResult",
    "Provenance",
    "ReleaseAssetResult",
    "RuntimeComparisonResult",
    "RuntimeRPCError",
    "SpatialNormalizationReport",
    "SpatialMappingSample",
    "SkinTransferReport",
    "SkinTransferResult",
    "Unified3DClient",
    "canonicalize_analysis",
    "compare_analyses",
    "compare_analyses_oracle",
    "normalize_analysis",
    "validate_analysis",
]

__version__ = "0.2.0.dev0"
